export type Song = {
  title: string;
  singer:string;
  category:string;
  audioPath: string;
};

export const songs: Song[] = [
  //12
  // {
  //   id: 1,
  //   title: "Man Ye Sahib Ji",
  //   singer: "Shreya Ghoshal",
  //   category: "fav",
  //   audioPath: "./fav/ManYeSahibJi.mp3",
  // },
  // {
  //   id: 2,
  //   title: "Labon Pe Naam",
  //   singer: "Armaan Malik",
  //   category: "fav",
  //   audioPath: "./fav/LabonPeNaam.mp3",
  // },
  // {
  //   id: 3,
  //   title: "Kabhi Yaadon Mein",
  //   singer: "Arijit Singh, Palak Muchhal",
  //   category: "fav",
  //   audioPath: "./fav/KabhiYaadonMein.mp3",
  // },
  // {
  //   id: 4,
  //   title: "Haareya",
  //   singer: "Arijit Singh",
  //   category: "fav",
  //   audioPath: "./fav/Haareya.mp3",
  // },
  // {
  //   id: 5,
  //   title: "Rozana",
  //   singer: "Shreya Ghoshal",
  //   category: "fav",
  //   audioPath: "./fav/Rozana.mp3",
  // },
  // {
  //   id: 6,
  //   title: "Sahiba",
  //   singer: "Stebin Ben",
  //   category: "fav",
  //   audioPath: "./fav/Sahiba.mp3",
  // },
  // {
  //   id: 7,
  //   title: "Udd Jaa Parindey",
  //   singer: "Amit Trivedi, Shahid Mallya",
  //   category: "fav",
  //   audioPath: "./fav/UddJaaParindey.mp3",
  // },
  // {
  //   id: 8,
  //   title: "Sab Tera",
  //   singer: "Armaan Malik, Shraddha Kapoor",
  //   category: "fav",
  //   audioPath: "./fav/SabTera.mp3",
  // },
  // {
  //   id: 9,
  //   title: "Dekha Hazaro Dafaa",
  //   singer: "Arijit Singh, Palak Muchhal",
  //   category: "fav",
  //   audioPath: "./fav/DekhaHazaroDafaa.mp3",
  // },
  // {
  //   id: 10,
  //   title: "Naino Ne Baandhi",
  //   singer: "Yasser Desai",
  //   category: "fav",
  //   audioPath: "./fav/NainoNeBaandhi.mp3",
  // },
  // {
    
  //   title: "Dil Jaaniye",
  //   singer: "Jubin Nautiyal",
  //   category: "fav",
  //   audioPath: "./fav/DilJaaniye.mp3",
  // },
  // {
  //   id: 12,
  //   title: "Aashiqui Aa Gayi",
  //   singer: "Arijit Singh",
  //   category: "fav",
  //   audioPath: "./fav/AashiquiAaGayi.mp3",
  // },
  // {
  //   id: 13,
  //   title: "Tere Sang Yaara",
  //   singer: "Atif Aslam",
  //   category: "fav",
  //   audioPath: "./fav/TereSangYaara.mp3",
  // },

// 7
// {
//     title: "Tenu Na Bol Pawaan",
//     singer: "Yasser Desai",
//     category: "song1",
//     audioPath: "./Fav/TenuNaBolPawaan.mp3",
//   },
//   {
//     title: "Teri Hogaiyaan",
//     singer: "Vishal Mishra",
//     category: "song1",
//     audioPath: "./Fav/TeriHogaiyaan.mp3",
//   },
//   {
//     title: "Besabriyaan",
//     singer: "Armaan Malik",
//     category: "song1",
//     audioPath: "./Fav/Besbriyaan.mp3",
//   },
  // {
  //   title: "Tera Chehra",
  //   singer: "Adnan Sami",
  //   category: "song1",
  //   audioPath: "./Fav/Tera Chehra.mp3",
  // },
  // {
  //   title: "Meri Hasi",
  //   singer: "Yasser Desai",
  //   category: "song1",
  //   audioPath: "./Fav/MeriHasi.mp3",
  // },
  // {
  //   title: "Chaiyaan Mein Saiyaan Ki",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Fav/ChaiyaanMeinSaiyaanKi.mp3",
  // },
  // {
  //   title: "Jitni Dafa",
  //   singer: "Yasser Desai",
  //   category: "song1",
  //   audioPath: "./Fav/JitniDafa.mp3",
  // },



 //19
  // {
  //   title: "Kesariya",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Kesariya.mp3",
  // },
  // {
  //   title: "Dil Jhoom",
  //   singer: "Arijit Singh, Mithoon",
  //   category: "song1",
  //   audioPath: "./Music/Dil Jhoom.mp3",
  // },
  // {
  //   title: "Enna Sona",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Enna Sona.mp3",
  // },
  // {
  //   title: "Dil Meri Na Sune",
  //   singer: "Atif Aslam",
  //   category: "song1",
  //   audioPath: "./Music/Dil Meri Na Sune.mp3",
  // },
  // {
  //   title: "Jeene Laga Hoon",
  //   singer: "Atif Aslam, Shreya Ghoshal",
  //   category: "song1",
  //   audioPath: "./Music/Jeene Laga Hoon.mp3",
  // },
  // {
  //   title: "Deva Deva",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Deva Deva Brahmastra 128 Kbps.mp3",
  // },
  // {
  //   title: "Hawayein",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Hawayein.mp3",
  // },
  // {
  //   title: "Kabhi Jo Baadal Barse",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Kabhi Jo Badal Barse.mp3",
  // },
  // {
  //   title: "Jashn-E-Bahaaraa",
  //   singer: "Javed Ali",
  //   category: "song1",
  //   audioPath: "./Music/Jashn E Bahaaraa.mp3",
  // },
  // {
  //   title: "Apna Bana Le",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Apna Bana Le.mp3",
  // },
  // {
  //   title: "Bahara",
  //   singer: "Shreya Ghoshal, Sukhwinder Singh",
  //   category: "song1",
  //   audioPath: "./Music/Bahara.mp3",
  // },
  // {
  //   title: "Kaun Tujhe",
  //   singer: "Palak Muchhal",
  //   category: "song1",
  //   audioPath: "./Music/Kaun Tujhe.mp3",
  // },
  // {
  //   title: "Dildaara",
  //   singer: "Shafqat Amanat Ali",
  //   category: "song1",
  //   audioPath: "./Music/Dildaara.mp3",
  // },
  // {
  //   title: "Chale Aana",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Chale Aana.mp3",
  // },
  // {
  //   title: "Chahun Main Ya Naa",
  //   singer: "Arijit Singh, Palak Muchhal",
  //   category: "song1",
  //   audioPath: "./Music/Chahun Main Ya Naa.mp3",
  // },
  // {
  //   title: "Chashni",
  //   singer: "Abhijeet Srivastava",
  //   category: "song1",
  //   audioPath: "./Music/Chashni.mp3",
  // },
  // {
  //   title: "Jag Ghoomeya",
  //   singer: "Rahat Fateh Ali Khan",
  //   category: "song1",
  //   audioPath: "./Music/Jag Ghoomeya.mp3",
  // },
  // {
  //   title: "Allah Waariyan",
  //   singer: "Shafqat Amanat Ali",
  //   category: "song1",
  //   audioPath: "./Music/Allah Waariyan.mp3",
  // },
  // {
  //   title: "Kaise Mujhe",
  //   singer: "Benny Dayal, Shreya Ghoshal",
  //   category: "song1",
  //   audioPath: "./Music/Kaise Mujhe.mp3",
  // },


//17
  // {
  //   title: "Leja Re",
  //   singer: "Dhvani Bhanushali",
  //   category: "song1",
  //   audioPath: "./Music/Leja Re.mp3",
  // },
  // {
  //   title: "Main Rang Sharbaton Ka",
  //   singer: "Atif Aslam, Chinmayi Sripada",
  //   category: "song1",
  //   audioPath: "./Music/Main Rang Sharbaton Ka.mp3",
  // },
  // {
  //   title: "Maan Meri Jaan",
  //   singer: "King",
  //   category: "song1",
  //   audioPath: "./Music/Man Meri Jan.mp3",
  // },
  // {
  //   title: "O Saathi",
  //   singer: "Atif Aslam",
  //   category: "song1",
  //   audioPath: "./Music/O Saathi.mp3",
  // },
  // {
  //   title: "Pal",
  //   singer: "Arijit Singh, Shreya Ghoshal",
  //   category: "song1",
  //   audioPath: "./Music/Pal.mp3",
  // },
  // {
  //   title: "Raataan Lambiyan",
  //   singer: "Jubin Nautiyal, Asees Kaur",
  //   category: "song1",
  //   audioPath: "./Music/Raataan Lambiyan.mp3",
  // },
  // {
  //   title: "Ranjha",
  //   singer: "Jasleen Royal, B Praak",
  //   category: "song1",
  //   audioPath: "./Music/Ranjha.mp3",
  // },
  // {
  //   title: "Roke Na Ruke Naina",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Roke Na Ruke Naina.mp3",
  // },
  // {
  //   title: "Samjhawan",
  //   singer: "Arijit Singh, Shreya Ghoshal",
  //   category: "song1",
  //   audioPath: "./Music/Samjhawan.mp3",
  // },
  // {
  //   title: "Sanam Re",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Sanam Re.mp3",
  // },
  // {
  //   title: "Tera Ban Jaunga",
  //   singer: "Tulsi Kumar, Akhil Sachdeva",
  //   category: "song1",
  //   audioPath: "./Music/Tera Ban Jaunga.mp3",
  // },
  // {
  //   title: "Tera Fitoor",
  //   singer: "Arijit Singh",
  //   category: "song1",
  //   audioPath: "./Music/Tera Fitoor.mp3",
  // },
  // {
  //   title: "Tera Hone Laga Hoon",
  //   singer: "Atif Aslam, Alisha Chinai",
  //   category: "song1",
  //   audioPath: "./Music/Tera Hone Laga Hoon.mp3",
  // },
  // {
  //   title: "Tere Bin",
  //   singer: "Rahat Fateh Ali Khan, Asees Kaur",
  //   category: "song1",
  //   audioPath: "./Music/Tere Bin.mp3",
  // },
  // {
  //   title: "Tu Jaane Na",
  //   singer: "Atif Aslam",
  //   category: "song1",
  //   audioPath: "./Music/Tu Jaane Na.mp3",
  // },
  // {
  //   title: "Tum Se",
  //   singer: "Raghav Chaitanya",
  //   category: "song1",
  //   audioPath: "./Music/Tum Se.mp3",
  // },
  // {
  //   title: "Vaaste",
  //   singer: "Dhvani Bhanushali, Nikhil D'Souza",
  //   category: "song1",
  //   audioPath: "./Music/Vaaste.mp3",
  // },


  // {
  //   title: "Banjaara",
  //   singer: "Mohammed Irfan",
  //   category: "song2",
  //   audioPath: "./song2/Banjaara.mp3",
  // },
  // {
  //   title: "Darmiyaan",
  //   singer: "Shafqat Amanat Ali, Clinton Cerejo",
  //   category: "song2",
  //   audioPath: "./song2/Darmiyaan.mp3",
  // },
  // {
  //   title: "Dehleez Pe Mere Dil Ki",
  //   singer: "Atif Aslam",
  //   category: "song2",
  //   audioPath: "./song2/DehleezPeMere.mp3",
  // },
  // {
  //   title: "Dil Ko Karaar Aaya (Reprise)",
  //   singer: "Neha Kakkar, Rajat Nagpal",
  //   category: "song2",
  //   audioPath: "./song2/DilKoKaraarAaya.mp3",
  // },
  // {
  //   title: "Hua Hain Aaj Pehli Baar",
  //   singer: "Armaan Malik, Palak Muchhal",
  //   category: "song2",
  //   audioPath: "./song2/HuaHainAajPehliBaar.mp3",
  // },
  // {
  //   title: "Humdard",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/Humdard.mp3",
  // },
  // {
  //   title: "Ik Vaari Aa",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/IkVaariAa.mp3",
  // },
  // {
  //   title: "Kehte Hain Khuda Ne",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/KehteHainKhuda.mp3",
  // },
  // {
  //   title: "Khamoshiyan",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/Khamoshiyan.mp3",
  // },
  // {
  //   title: "Pal Pal Dil Ke Paas",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/PalPalDilKePaas.mp3",
  // },
  // {
  //   title: "Raat Bhar",
  //   singer: "Arijit Singh, Shreya Ghoshal",
  //   category: "song2",
  //   audioPath: "./song2/RaatBhar.mp3",
  // },
  // {
  //   title: "Rabba Janda",
  //   singer: "Jubin Nautiyal",
  //   category: "song2",
  //   audioPath: "./song2/RabbaJanda.mp3",
  // },
  // {
  //   title: "Rahna Tu",
  //   singer: "A.R. Rahman",
  //   category: "song2",
  //   audioPath: "./song2/RahnaTu.mp3",
  // },
  // {
  //   title: "Rang Jo Lagyo",
  //   singer: "Atif Aslam, Shreya Ghoshal",
  //   category: "song2",
  //   audioPath: "./song2/RangJoLagyo.mp3",
  // },
  // {
  //   title: "Sajni",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/SajniRe.mp3",
  // },
  // {
  //   title: "Sau Aasmaan",
  //   singer: "Armaan Malik, Neeti Mohan",
  //   category: "song2",
  //   audioPath: "./song2/SauAasmaan.mp3",
  // },
  // {
  //   title: "Sooraj Dooba Hain",
  //   singer: "Arijit Singh, Amaal Mallik",
  //   category: "song2",
  //   audioPath: "./song2/SoorajDoobaHain.mp3",
  // },
  // {
  //   title: "Sun Mere Humsafar",
  //   singer: "Akhil Sachdeva, Mansheel Gujral",
  //   category: "song2",
  //   audioPath: "./song2/SunMereHumsafar.mp3",
  // },
  // {
  //   title: "Suno Na Sangemarmar",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/SunoNaSangemarmar.mp3",
  // },
  // {
  //   title: "Tera Yaar Hoon Main",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/TeraYaarHoonMain.mp3",
  // },
  // {
  //   title: "Tu Thodi Der Aur Thehar Ja",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./song2/TuThodiDerAurTheharJa.mp3",
  // },

  // {
  //   title: "Thoda Hans Ke",
  //   singer: "Anuj Gurwara",
  //   category: "song3",
  //   audioPath: "./Song3/ThodaHansKe.mp3",
  // },
  // {
  //   title: "You Are My Soniya",
  //   singer: "Sonu Nigam, Alka Yagnik",
  //   category: "song3",
  //   audioPath: "./Song3/You Are My Soniya.mp3",
  // },
  // {
  //   title: "Tujh Mein Rab Dikhta Hai",
  //   singer: "Roop Kumar Rathod",
  //   category: "song3",
  //   audioPath: "./Song3/TujhMeinRabDikhtaHai.mp3",
  // },
  // {
  //   title: "Pehli Nazar Mein",
  //   singer: "Atif Aslam",
  //   category: "song3",
  //   audioPath: "./Song3/Pehli Nazar.mp3",
  // },
  // {
  //   title: "Paniyon Sa",
  //   singer: "Atif Aslam, Tulsi Kumar",
  //   category: "song3",
  //   audioPath: "./Song3/Paniyon Sa.mp3",
  // },
  // {
  //   title: "Tu Jo Mila",
  //   singer: "KK",
  //   category: "song3",
  //   audioPath: "./Song3/Tu JoMila.mp3",
  // },
  // {
  //   title: "Pehli Dafa",
  //   singer: "Atif Aslam",
  //   category: "song3",
  //   audioPath: "./Song3/PehliDafa.mp3",
  // },
  // {
  //   title: "Piya O Re Piya",
  //   singer: "Atif Aslam, Shreya Ghoshal",
  //   category: "song3",
  //   audioPath: "./Song3/PiyaORePiya.mp3",
  // },
  // {
  //   title: "Tere Liye",
  //   singer: "Atif Aslam, Shreya Ghoshal",
  //   category: "song3",
  //   audioPath: "./Song3/TereLiye.mp3",
  // },
  // {
  //   title: "Dil Diyan Gallan",
  //   singer: "Atif Aslam",
  //   category: "song3",
  //   audioPath: "./Song3/DilDiyanGallan.mp3",
  // },
  // {
  //   title: "Falak Tak",
  //   singer: "Udit Narayan, Mahalaxmi Iyer",
  //   category: "song3",
  //   audioPath: "./Song3/FalakTak.mp3",
  // },
  // {
  //   title: "Tu Hi Yaar Mera",
  //   singer: "Arijit Singh, Neha Kakkar",
  //   category: "song3",
  //   audioPath: "./Song3/TuHiYaarMera.mp3",
  // },
  // {
  //   title: "Teri Ore",
  //   singer: "Rahat Fateh Ali Khan, Shreya Ghoshal",
  //   category: "song3",
  //   audioPath: "./Song3/TeriOre.mp3",
  // },
  // {
  //   title: "Baarish Ban Jaana",
  //   singer: "Stebin Ben, Payal Dev",
  //   category: "song3",
  //   audioPath: "./Song3/BaarishBanJaana.mp3",
  // },
  // {
  //   title: "Nadaaniyan",
  //   singer: "Akshath",
  //   category: "song3",
  //   audioPath: "./Song3/Nadaaniyan.mp3",
  // },
  // {
  //   title: "Mere Sawaal Ka",
  //   singer: "Shashwat Singh",
  //   category: "song3",
  //   audioPath: "./Song3/MereSawaalKa.mp3",
  // },
  // {
  //   title: "Kabira",
  //   singer: "Arijit Singh, Tochi Raina",
  //   category: "song3",
  //   audioPath: "./Song3/Kabira.mp3",
  // },
  // {
  //   title: "Jogi",
  //   singer: "Yasser Desai, Aakanksha Sharma",
  //   category: "song3",
  //   audioPath: "./Song3/JogiHona.mp3",
  // },
  // {
  //   title: "O Bekhabar",
  //   singer: "Shreya Ghoshal",
  //   category: "song3",
  //   audioPath: "./Song3/OBekhabar.mp3",
  // },
  // {
  //   title: "Mast Magan",
  //   singer: "Arijit Singh, Chinmayi",
  //   category: "song3",
  //   audioPath: "./Song3/MastMagan.mp3",
  // },
  // {
  //   title: "Jab Tak",
  //   singer: "Armaan Malik",
  //   category: "song3",
  //   audioPath: "./Song3/JabTak.mp3",
  // },

  // {
  //   title: "Mere Naam Tu",
  //   singer: "Abhay Jodhpurkar",
  //   category: "song3",
  //   audioPath: "./song3/MereNaamTu.mp3",
  // },
  // {
  //   title: "Kuch To Hai",
  //   singer: "Armaan Malik",
  //   category: "song3",
  //   audioPath: "./song3/KuchToHai.mp3",
  // },
  // {
  //   title: "Dekhha Tenu",
  //   singer: "Mohammad Faiz",
  //   category: "song3",
  //   audioPath: "./song3/DekhhaTenu.mp3",
  // },
  // {
  //   title: "Dheere Dheere",
  //   singer: "Yo Yo Honey Singh",
  //   category: "song3",
  //   audioPath: "./song3/DheereDheereSe.mp3",
  // },
  // {
  //   title: "Mere Yaaraa",
  //   singer: "Arijit Singh, Neeti Mohan",
  //   category: "song3",
  //   audioPath: "./song3/MereYaraa.mp3",
  // },
  // {
  //   title: "Yaara",
  //   singer: "Mamta Sharma",
  //   category: "song3",
  //   audioPath: "./song3/Yaara.mp3",
  // },
  // {
  //   title: "Mitra Re",
  //   singer: "Arijit Singh, Jasleen Royal",
  //   category: "song3",
  //   audioPath: "./song3/MitraRe.mp3",
  // },
  // {
  //   title: "Ve Haaniyaan",
  //   singer: "Danny, Avvy Sra",
  //   category: "song3",
  //   audioPath: "./song3/VeHaaniyaan.mp3",
  // },
  // {
  //   title: "Saathiya",
  //   singer: "Sonu Nigam",
  //   category: "song3",
  //   audioPath: "./song3/Saathiya.mp3",
  // },
  // {
  //   title: "Sukoon Mila",
  //   singer: "Arijit Singh",
  //   category: "song3",
  //   audioPath: "./song3/SukoonMila.mp3",
  // },
  // {
  //   title: "Main Koi Aisa Geet Gaoon",
  //   singer: "Abhijeet Bhattacharya",
  //   category: "song3",
  //   audioPath: "./song3/MainKoiAisaGeetGaoon.mp3",
  // },
  // {
  //   title: "Teri Meri Kahani",
  //   singer: "Arijit Singh",
  //   category: "song3",
  //   audioPath: "./song3/TeriMeriKahani.mp3",
  // },
  // {
  //   title: "Teri Meri Prem Kahani",
  //   singer: "Rahat Fateh Ali Khan, Shreya Ghoshal",
  //   category: "song3",
  //   audioPath: "./song3/TeriMeriPremKahani.mp3",
  // },
  // {
  //   title: "Jab Koi Baat",
  //   singer: "Atif Aslam",
  //   category: "song3",
  //   audioPath: "./song3/JabKoiBaat.mp3",
  // },
  // {
  //   title: "Lo Safar",
  //   singer: "Jubin Nautiyal",
  //   category: "song3",
  //   audioPath: "./song3/LoSafar.mp3",
  // },
  // {
  //   title: "Kashmir Main Tu Kanyakumari",
  //   singer: "Arijit Singh, Sunidhi Chauhan",
  //   category: "song3",
  //   audioPath: "./song3/KashmirMainTuKanyakumari.mp3",
  // },
  // {
  //   title: "Titli",
  //   singer: "Chinmayi Sripada",
  //   category: "song3",
  //   audioPath: "./song3/TitliDiUda.mp3",
  // },
  // {
  //   title: "Pyaar Ka Dard Hai",
  //   singer: "Rahat Fateh Ali Khan",
  //   category: "song3",
  //   audioPath: "./song3/PyaarKaDardHai.mp3",
  // },
  // {
  //   title: "Ve Maahi",
  //   singer: "Arijit Singh",
  //   category: "song3",
  //   audioPath: "./song3/VeMaahi.mp3",
  // },
  // {
  //   title: "Kal Ho Naa Ho",
  //   singer: "Sonu Nigam",
  //   category: "song3",
  //   audioPath: "./song3/KalHoNaaHo.mp3",
  // },
  // {
  //   title: "O Jaana",
  //   singer: "Udit Narayan",
  //   category: "song3",
  //   audioPath: "./song3/OJaana.mp3",
  // },

 
  // {
  //   title: "Tere Dil Ka Rishta",
  //   singer: "Sonu Nigam",
  //   category: "song2",
  //   audioPath: "./Song3/TereDilKaRishta.mp3",
  // },
  // {
  //   title: "Manwa Laage",
  //   singer: "Arijit Singh, Shreya Ghoshal",
  //   category: "song2",
  //   audioPath: "./Song3/ManwaLaage.mp3",
  // },
  // {
  //   title: "Ye hai Mohhabaten",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./Song3/Dil ahiRukta.mp3",
  // },
  // {
  //   title: "Nazm Nazm",
  //   singer: "Arko",
  //   category: "song2",
  //   audioPath: "./Song3/NazmNazm.mp3",
  // },
  // {
  //   title: "Ye Tahar",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./Song3/YeTahar.mp3",
  // },
  // {
  //   title: "Jaan Ban Gaye",
  //   singer: "Mithoon, Vishal Mishra, Asees Kaur",
  //   category: "song2",
  //   audioPath: "./Song3/JaanBanGaye.mp3",
  // },
  // {
  //   title: "Badmaash Dil",
  //   singer: "Benny Dayal",
  //   category: "song2",
  //   audioPath: "./Song3/BadmasDilDagHaiBada.mp3",
  // },
  // {
  //   title: "Tose Naina",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./Song3/ToseNaina.mp3",
  // },
  // {
  //   title: "Aaj Sajeya",
  //   singer: "Goldie Sohel",
  //   category: "song2",
  //   audioPath: "./Song3/AajSajeya.mp3",
  // },
  // {
  //   title: "Channa Ve",
  //   singer: "Akhil Sachdeva",
  //   category: "song2",
  //   audioPath: "./Song3/ChannaVe.mp3",
  // },
  // {
  //   title: "Channa Mereya",
  //   singer: "Arijit Singh",
  //   category: "song2",
  //   audioPath: "./Song3/ChannaMereya.mp3",
  // },

  //   {
  //   title: "Bhagwan Hai Kahan Re Tu",
  //   singer: "Sonu Nigam",
  //   category: "spritual",
  //   audioPath: "./Spritual/BhagwanHaiKahanReTu.mp3",
  // },
  // {
  //   title: "Kaun Hain Woh",
  //   singer: "Kailash Kher",
  //   category: "spritual",
  //   audioPath: "./Spritual/KaunHainVoh.mp3",
  // },
  // {
  //   title: "Laagi Lagan Shankara",
  //   singer: "Hansraj Raghuwanshi",
  //   category: "spritual",
  //   audioPath: "./Spritual/LaagiLaganShankara.mp3",
  // },
  // {
  //   title: "Mera Bhola Bhandari",
  //   singer: "Hansraj Raghuwanshi",
  //   category: "spritual",
  //   audioPath: "./Spritual/MeraBholaBhandari.mp3",
  // },
  // {
  //   title: "Mere Nishaan",
  //   singer: "Meet Bros, Kailash Kher",
  //   category: "spritual",
  //   audioPath: "./Spritual/MereNishaan.mp3",
  // },
  // {
  //   title: "Namo Namo Ji Shankara",
  //   singer: "Amit Trivedi",
  //   category: "spritual",
  //   audioPath: "./Spritual/Namo Namo Ji Shankara.mp3",
  // },
  // {
  //   title: "Parvati Boli Shankar Se",
  //   singer: "Hansraj Raghuwanshi",
  //   category: "spritual",
  //   audioPath: "./Spritual/Parvati Boli Shankar Se.mp3",
  // },
];






